# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tasks_service.proto.tasks_service_pb2 as tasks__service__pb2


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/TaskService/CreateTask',
                request_serializer=tasks__service__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=tasks__service__pb2.ITask.FromString,
                )
        self.UpdateTask = channel.unary_unary(
                '/TaskService/UpdateTask',
                request_serializer=tasks__service__pb2.UpdateTaskRequest.SerializeToString,
                response_deserializer=tasks__service__pb2.UpdateTaskResponse.FromString,
                )
        self.DeleteTask = channel.unary_unary(
                '/TaskService/DeleteTask',
                request_serializer=tasks__service__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=tasks__service__pb2.DeleteTaskResponse.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/TaskService/GetTask',
                request_serializer=tasks__service__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=tasks__service__pb2.GetTaskResponse.FromString,
                )
        self.GetTasksList = channel.unary_unary(
                '/TaskService/GetTasksList',
                request_serializer=tasks__service__pb2.GetTasksListRequest.SerializeToString,
                response_deserializer=tasks__service__pb2.GetTasksListResponse.FromString,
                )


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasksList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=tasks__service__pb2.CreateTaskRequest.FromString,
                    response_serializer=tasks__service__pb2.ITask.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=tasks__service__pb2.UpdateTaskRequest.FromString,
                    response_serializer=tasks__service__pb2.UpdateTaskResponse.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=tasks__service__pb2.DeleteTaskRequest.FromString,
                    response_serializer=tasks__service__pb2.DeleteTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=tasks__service__pb2.GetTaskRequest.FromString,
                    response_serializer=tasks__service__pb2.GetTaskResponse.SerializeToString,
            ),
            'GetTasksList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasksList,
                    request_deserializer=tasks__service__pb2.GetTasksListRequest.FromString,
                    response_serializer=tasks__service__pb2.GetTasksListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskService/CreateTask',
            tasks__service__pb2.CreateTaskRequest.SerializeToString,
            tasks__service__pb2.ITask.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskService/UpdateTask',
            tasks__service__pb2.UpdateTaskRequest.SerializeToString,
            tasks__service__pb2.UpdateTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskService/DeleteTask',
            tasks__service__pb2.DeleteTaskRequest.SerializeToString,
            tasks__service__pb2.DeleteTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskService/GetTask',
            tasks__service__pb2.GetTaskRequest.SerializeToString,
            tasks__service__pb2.GetTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTasksList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TaskService/GetTasksList',
            tasks__service__pb2.GetTasksListRequest.SerializeToString,
            tasks__service__pb2.GetTasksListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
