@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/latest/C4_Context.puml

LAYOUT_LANDSCAPE()

Person(user, "User", "Пользователь трекера задач")
System(taskTracker, "Task Tracker", "Сервис для менеджмента пользовательских задач")

Rel(user, taskTracker, "Регистрация, аутентификация")
Rel(user, taskTracker, "Создание задач, обновление и удаление постов, получать задачи сгруппированные по статусам")
Rel(user, taskTracker, "Оставлять комментарии к задачам, ставить лайки")
Rel(user, taskTracker, "Статистика по просмотрам и лайкам")


@enduml
