openapi: 3.0.0
info: 
  title: Main Servide API
  version: 1.0.0
paths:
  /signup:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешная регистрация
          headers:
            Set-cookie:
              description: Куки для работы с сервисом
              schema:
                type: string
        '403':
          description: Пользователь уже существует
  /login:
    get:
      summary: Аутентификация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешная авторизация
          headers:
            Set-cookie:
              description: Куки для работы с сервисом
              schema:
                type: string
        '401':
          description: Неверный пароль к логину
        '403':
          description: Пользователя с таким логином не существует
  /update:
    post:
      security:
        - AuthToken: []
      summary: Обновление данных пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  nullable: true
                lastName:
                  type: string
                  nullable: true
                birthDate:
                  type: string
                  format: date
                  nullable: true
                mail:
                  type: string
                  format: email
                  nullable: true
                phoneNumber:
                  type: string
                  nullable: true        
      responses:
        '200':
          description: Успешное обновление данных пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                    nullable: true
                    nullable: true
                    format: date
                    nullable: true
                    format: email
                    nullable: true
                    nullable: true
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
  /tasks/create:
    post:
      security:
        - AuthToken: []
      summary: Создание задачи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                status:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Успешное создание задачи
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет title или content
  /tasks/update:
    put:
      security:
        - AuthToken: []
      summary: Обновление задачи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
                title:
                  type: string
                  nullable: true
                content:
                  type: string
                  nullable: true
                status:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Успешное обновление задачи
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
        '404':
          description: Невалидный запрос
        '405':
          description: Невалидный taskId
  /tasks/delete:
    delete:
      security:
        - AuthToken: []
      summary: Удаление задачи
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
      responses:
        '200':
          description: Успешное удаление задачи
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
        '405':
          description: Невалидный taskId
  /tasks/get:
    get:
      security:
        - AuthToken: []
      summary: Получить задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
      responses:
        '200':
          description: Успешное получение задачи
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
        '406':
          description: Невалидный taskId
  /tasks/get_page:
    get:
      security:
        - AuthToken: []
      summary: Получить страницу с задачами
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authorLogin:
                  type: string
                pageSize:
                  type: integer
                page:
                  type: integer
      responses:
        '200':
          description: Успешное получение страницы с задачами
          content:
            application/json:
              schema:
                type: array
                properties:
                  id:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет pageSize или page
        '406':
          description: pageSize должно быть положительным числом
  /statistics/send_view:
    post:
      security:
        - AuthToken: []
      summary: Отправить просмотр по задаче
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
      responses:
        '200':
          description: Запрос о просмотре успешно отправлен
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
  /statistics/send_like:
    post:
      security:
        - AuthToken: []
      summary: Поставить лайк на задачу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
      responses:
        '200':
          description: Запрос о лайке успешно отправлен
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
  /statistics/get_stats:
    get:
      security:
        - AuthToken: []
      summary: Получить статистику по задаче
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: integer
      responses:
        '200':
          description: Успешное получение задачи
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: integer
                  likes:
                    type: integer
                  views:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
        '406':
          description: Невалидный taskId
  /statistics/get_top_tasks:
    get:
      security:
        - AuthToken: []
      summary: Получить топ задач
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: boolean
      responses:
        '200':
          description: Успешное получение топа задач
          content:
            application/json:
              schema:
                type: array
                properties:
                  taskId:
                    type: integer
                  count:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
        '403':
          description: В запросе нет taskId
  /statistics/get_top_users:
    get:
      security:
        - AuthToken: []
      summary: Получить топ пользователей
      responses:
        '200':
          description: Успешное получение топа пользователей
          content:
            application/json:
              schema:
                type: array
                properties:
                  login:
                    type: integer
                  likes:
                    type: integer
        '400': 
          description: Нет куки
        '401':
          description: Невалидная кука
components:
  securitySchemes:
    AuthToken:
      type: http
      scheme: bearer
      bearerFormat: JWT