openapi: 3.0.0
info: 
  title: Main Servide API
  version: 1.0.0
paths:
  /signup:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешная регистрация
          headers:
            Set-cookie:
              description: Куки для работы с сервисом
              schema:
                type: string
        '403':
          description: Пользователь уже существует
  /login:
    post:
      summary: Аутентификация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешная авторизация
          headers:
            Set-cookie:
              description: Куки для работы с сервисом
              schema:
                type: string
        '401':
          description: Пользователя с таким логином не существует
        '403':
          description: Неверный пароль к логину
  /update:
    post:
      security:
        - AuthToken: []
      summary: Обновление данных пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  nullable: true
                lastName:
                  type: string
                  nullable: true
                birthDate:
                  type: string
                  format: date
                  nullable: true
                mail:
                  type: string
                  format: email
                  nullable: true
                phoneNumber:
                  type: string
                  nullable: true
                  
      responses:
        '200':
          description: Успешное обновление данных пользователя
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                    nullable: true
                  lastName:
                    type: string
                    nullable: true
                  birthDate:
                    type: string
                    format: date
                    nullable: true
                  mail:
                    type: string
                    format: email
                    nullable: true
                  phoneNumber:
                    type: string
                    nullable: true
        '401': 
          description: Нет куки
        '400':
          description: Невалидная кука
components:
  securitySchemes:
    AuthToken:
      type: http
      scheme: bearer
      bearerFormat: JWT