version: '3.5'
 
services:
    database:
        build: 
            context: main_service/database
        ports:
            - 8091:8090
        volumes:
            - ./main_service/database/database.db:/main_service/database/database.db
 
    tasks_database:
        image: postgres:latest
        environment:
            POSTGRES_DB: tasks_db
            POSTGRES_USER: tasks_service_login
            POSTGRES_PASSWORD: megapassword52fortasksservice
        ports:
            - 5432:5432

    zookeeper:
        image: bitnami/zookeeper:latest
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - "2181:2181"

    kafka:
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper

    kafka_topics:
        image: bitnami/kafka:latest
        depends_on:
            - kafka
        entrypoint: [ '/bin/sh', '-c' ]
        command: "kafka-topics.sh --create --topic likes_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 && \
        kafka-topics.sh --create --topic views_topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1"

    clickhouse:
        image: yandex/clickhouse-server:latest
        ports:
            - 8123:8123
            - 9000:9000
        environment:
            - CLICKHOUSE_DB=default
        depends_on:
            - kafka
 
    server:
        build: 
            context: .
            dockerfile: main_service/server/Dockerfile
        ports:
            - 8090:8090
        depends_on:
            - database
            - kafka
        restart: on-failure:10

    tasks_server:
        build: 
            context: tasks_service
        ports:
            - 5051:5050
        depends_on:
            - tasks_database

    statistics_server:
        build: 
            context: .
            dockerfile: statistics_service/Dockerfile
        ports:
            - 8092:8092
            - 5050:5050
        depends_on:
            - kafka
            - clickhouse
            - kafka_topics
        restart: on-failure:10

