version: '3.5'
 
services:
    database:
        build: 
            context: main_service/database
        ports:
            - 8091:8090
        volumes:
            - ./main_service/database/database.db:/main_service/database/database.db
 
    tasks_database:
        image: postgres:latest
        environment:
            POSTGRES_DB: tasks_db
            POSTGRES_USER: tasks_service_login
            POSTGRES_PASSWORD: megapassword52fortasksservice
        ports:
            - 5432:5432
 
    server:
        build: 
            context: .
            dockerfile: main_service/server/Dockerfile
        ports:
            - 8090:8090
        depends_on:
            - database

    tasks_server:
        build: 
            context: tasks_service
        ports:
            - 5050:5050
        depends_on:
            - tasks_database

