# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18statistics_service.proto\"!\n\x0fGetStatsRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\x04\"0\n\x10GetStatsResponce\x12\r\n\x05likes\x18\x01 \x01(\x04\x12\r\n\x05views\x18\x02 \x01(\x04\"9\n\x12GetTopTasksRequest\x12\x13\n\x04type\x18\x01 \x01(\x0e\x32\x05.Type\x12\x0e\n\x06taskId\x18\x02 \x03(\x04\"*\n\tTaskStats\x12\x0e\n\x06taskId\x18\x01 \x01(\x04\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"0\n\x13GetTopTasksResponce\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.TaskStats\"*\n\tUserTasks\x12\r\n\x05login\x18\x01 \x01(\t\x12\x0e\n\x06taskId\x18\x02 \x03(\x04\"/\n\x12GetTopUsersRequest\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.UserTasks\")\n\tUserStats\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05likes\x18\x02 \x01(\x04\"0\n\x13GetTopUsersResponce\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.UserStats*\x1c\n\x04Type\x12\t\n\x05LIKES\x10\x00\x12\t\n\x05VIEWS\x10\x01\x32\xbe\x01\n\x11StatisticsService\x12\x31\n\x08GetStats\x12\x10.GetStatsRequest\x1a\x11.GetStatsResponce\"\x00\x12:\n\x0bGetTopTasks\x12\x13.GetTopTasksRequest\x1a\x14.GetTopTasksResponce\"\x00\x12:\n\x0bGetTopUsers\x12\x13.GetTopUsersRequest\x1a\x14.GetTopUsersResponce\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TYPE']._serialized_start=452
  _globals['_TYPE']._serialized_end=480
  _globals['_GETSTATSREQUEST']._serialized_start=28
  _globals['_GETSTATSREQUEST']._serialized_end=61
  _globals['_GETSTATSRESPONCE']._serialized_start=63
  _globals['_GETSTATSRESPONCE']._serialized_end=111
  _globals['_GETTOPTASKSREQUEST']._serialized_start=113
  _globals['_GETTOPTASKSREQUEST']._serialized_end=170
  _globals['_TASKSTATS']._serialized_start=172
  _globals['_TASKSTATS']._serialized_end=214
  _globals['_GETTOPTASKSRESPONCE']._serialized_start=216
  _globals['_GETTOPTASKSRESPONCE']._serialized_end=264
  _globals['_USERTASKS']._serialized_start=266
  _globals['_USERTASKS']._serialized_end=308
  _globals['_GETTOPUSERSREQUEST']._serialized_start=310
  _globals['_GETTOPUSERSREQUEST']._serialized_end=357
  _globals['_USERSTATS']._serialized_start=359
  _globals['_USERSTATS']._serialized_end=400
  _globals['_GETTOPUSERSRESPONCE']._serialized_start=402
  _globals['_GETTOPUSERSRESPONCE']._serialized_end=450
  _globals['_STATISTICSSERVICE']._serialized_start=483
  _globals['_STATISTICSSERVICE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
