# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import statistics_service.proto.statistics_service_pb2 as statistics__service__pb2


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStats = channel.unary_unary(
                '/StatisticsService/GetStats',
                request_serializer=statistics__service__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=statistics__service__pb2.GetStatsResponce.FromString,
                )
        self.GetTopTasks = channel.unary_unary(
                '/StatisticsService/GetTopTasks',
                request_serializer=statistics__service__pb2.GetTopTasksRequest.SerializeToString,
                response_deserializer=statistics__service__pb2.GetTopTasksResponce.FromString,
                )
        self.GetTopUsers = channel.unary_unary(
                '/StatisticsService/GetTopUsers',
                request_serializer=statistics__service__pb2.GetTopUsersRequest.SerializeToString,
                response_deserializer=statistics__service__pb2.GetTopUsersResponce.FromString,
                )


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=statistics__service__pb2.GetStatsRequest.FromString,
                    response_serializer=statistics__service__pb2.GetStatsResponce.SerializeToString,
            ),
            'GetTopTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopTasks,
                    request_deserializer=statistics__service__pb2.GetTopTasksRequest.FromString,
                    response_serializer=statistics__service__pb2.GetTopTasksResponce.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=statistics__service__pb2.GetTopUsersRequest.FromString,
                    response_serializer=statistics__service__pb2.GetTopUsersResponce.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StatisticsService/GetStats',
            statistics__service__pb2.GetStatsRequest.SerializeToString,
            statistics__service__pb2.GetStatsResponce.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StatisticsService/GetTopTasks',
            statistics__service__pb2.GetTopTasksRequest.SerializeToString,
            statistics__service__pb2.GetTopTasksResponce.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StatisticsService/GetTopUsers',
            statistics__service__pb2.GetTopUsersRequest.SerializeToString,
            statistics__service__pb2.GetTopUsersResponce.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
